services:
  postgres:
    image: postgres:17
    container_name: nextdb
    restart: unless-stopped
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME:-database}
      POSTGRES_USER: ${DB_USER:-aceplus}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-aceplus123}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
